ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "style(pre-commit.ci): auto fixes [...]"
  autoupdate_commit_msg: "ci(pre-commit.ci): autoupdate"

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
        exclude: ^(tests/data)
      - id: trailing-whitespace
        exclude: ^(tests/data)
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.13
    hooks:
      - id: validate-pyproject

#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.991
#     hooks:
#       - id: mypy
#         files: "^src/"
